# Generated by Django 4.1.7 on 2023-03-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_ID', models.EmailField(max_length=254, unique=True)),
                ('Full_Name', models.CharField(max_length=100)),
                ('College', models.CharField(max_length=250)),
                ('College_Roll_No', models.CharField(max_length=100)),
                ('Course', models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.Sc.', 'B.Sc.'), ('B.A', 'B.A'), ('M.Sc', 'M.Sc'), ('M.Tech', 'M.Tech')], max_length=20)),
                ('Branch', models.CharField(choices=[('CSE', 'CSE'), ('AI', 'AI'), ('ECE', 'ECE')], max_length=20)),
                ('Passing_Year', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('DOB', models.DateField()),
                ('Category', models.CharField(choices=[('General', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC')], max_length=20)),
                ('Contact_Number', models.IntegerField()),
                ('Skills', models.CharField(max_length=200)),
                ('Photo', models.FileField(upload_to='profile_photo/')),
                ('College_Id_Card', models.FileField(upload_to='clg_id_card/')),
                ('Resume', models.FileField(upload_to='resumes/')),
                ('Xth_Percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Xth_Marksheet', models.FileField(upload_to='10th_marksheet/')),
                ('XIIth_Percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('XIIth_Marksheet', models.FileField(upload_to='12th_marksheet/')),
                ('College_CGPA', models.DecimalField(decimal_places=2, max_digits=3)),
                ('College_Marksheets', models.FileField(upload_to='clg_marksheet/')),
            ],
        ),
    ]
