# Generated by Django 4.1.7 on 2023-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Branch',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('AI', 'AI'), ('ECE', 'ECE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Category',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='College_CGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='College_Id_Card',
            field=models.FileField(blank=True, upload_to='clg_id_card/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='College_Marksheets',
            field=models.FileField(blank=True, upload_to='clg_marksheet/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='College_Roll_No',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Contact_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Course',
            field=models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('B.Sc.', 'B.Sc.'), ('B.A', 'B.A'), ('M.Sc', 'M.Sc'), ('M.Tech', 'M.Tech')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Passing_Year',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=models.FileField(blank=True, upload_to='profile_photo/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Skills',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='XIIth_Marksheet',
            field=models.FileField(blank=True, upload_to='12th_marksheet/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='XIIth_Percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Xth_Marksheet',
            field=models.FileField(blank=True, upload_to='10th_marksheet/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Xth_Percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
