# Generated by Django 4.1.7 on 2023-03-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superset', '0003_alter_student_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uvstudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College_Name', models.CharField(max_length=250, unique=True)),
                ('File', models.FileField(upload_to='college_Students/')),
            ],
        ),
    ]
