# Generated by Django 4.1.7 on 2023-03-21 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superset', '0004_uvstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uvstudents',
            name='File',
            field=models.FileField(upload_to='college_Students/', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
