# Generated by Django 4.1.7 on 2023-03-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superset', '0007_student_approval_status_student_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='approval_status',
            field=models.CharField(choices=[('UA', 'Unapproved'), ('A', 'Approved')], default='UA', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_status',
            field=models.CharField(choices=[('UR', 'Unregistered'), ('R', 'Registered')], default='UR', max_length=20),
        ),
    ]
