# Generated by Django 4.1.7 on 2023-04-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superset', '0008_alter_student_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_ID', models.EmailField(max_length=254, unique=True)),
                ('Company_Name', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=500)),
                ('Address', models.CharField(max_length=300)),
            ],
        ),
    ]
