# Generated by Django 4.1.7 on 2023-04-10 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superset', '0009_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=100)),
                ('universities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superset.company')),
            ],
        ),
    ]
