# Generated by Django 4.1.7 on 2023-04-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superset', '0013_alter_company_universities_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_universities',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superset.company'),
        ),
    ]
