# Generated by Django 4.1.7 on 2023-04-10 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superset', '0014_alter_company_universities_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_universities',
            name='key',
        ),
        migrations.AlterField(
            model_name='company_universities',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superset.company'),
        ),
    ]
