# Generated by Django 4.1.7 on 2023-04-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superset', '0015_remove_company_universities_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(unique=True)),
                ('job_role', models.CharField(max_length=100)),
                ('CTC', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=200)),
                ('Xth_perecentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('XIIth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('College_CGPA', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('Company_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
