# Generated by Django 4.1.7 on 2023-05-02 06:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superset', '0016_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_universities',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comuv', to='superset.company'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_id',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.CreateModel(
            name='University_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universitiy', models.CharField(blank=True, max_length=100, null=True)),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentjob', to='superset.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('Application_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1)),
                ('Resume', models.FileField(upload_to='Job_Applicants/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='superset.jobs')),
            ],
        ),
    ]
